name: 🔑 Fabricar Keystore
on: workflow_dispatch
jobs:
  forjar:
    runs-on: ubuntu-latest
    steps:
      - name: Crear llave y convertir a texto
        run: |
          # 1. Generamos la llave con contraseñas por defecto (anekon123)
          keytool -genkey -v -keystore release.jks -keyalg RSA -keysize 2048 -validity 10000 -alias anekon_key -dname "CN=Rey, OU=Anekon, O=Anekon, L=Chihuahua, S=Chihuahua, C=MX" -storepass anekon123 -keypass anekon123
          
          # 2. La convertimos a Base64 y la guardamos en un archivo de texto
          base64 -w 0 release.jks > llaves_base64.txt
          
          # 3. Anotamos las contraseñas en el mismo archivo para que no se pierdan
          echo -e "\n\n--- TUS SECRETOS PARA GITHUB ---" >> llaves_base64.txt
          echo "KEYSTORE_PASSWORD=anekon123" >> llaves_base64.txt
          echo "KEY_ALIAS=anekon_key" >> llaves_base64.txt
          echo "KEY_PASSWORD=anekon123" >> llaves_base64.txt

      - name: Entregar paquete
        uses: actions/upload-artifact@v4
        with:
          name: mis-llaves
          path: llaves_base64.txt

